config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'landing#index', as: 'root'

  # yung namespace
  get   '/admin/dashboard',      to: 'admin/dashboard#show', as: 'admin_dashboard'

  get   '/admin/items',          to: 'admin/items#index',    as: 'admin_items'
  get   '/admin/items/new',      to: 'admin/items#new',      as: 'new_admin_item'
  get   '/admin/items/:id/edit', to: 'admin/items#edit',     as: 'edit_admin_item'
  get   '/admin/items/:id',      to: 'admin/items#show',     as: 'admin_item'
  post  '/admin/items',          to: 'admin/items#create'
  patch '/admin/items/:id',      to: 'admin/items#update'
  put   '/admin/items/:id',      to: 'admin/items#update'

  get   'admin/users/:id',      to: 'admin/users#show',  as: 'admin_user'
  get   'admin/users/:id/edit', to: 'admin/users#edit',  as: 'edit_admin_user'
  patch '/admin/users/:id',     to: 'admin/users#update'
  put   '/admin/users/:id',     to: 'admin/users#update'

  get 'admin/ordered',   to: 'admin/orders#index', as: 'admin_ordered'
  get 'admin/paid',      to: 'admin/orders#index', as: 'admin_paid'
  get 'admin/cancelled', to: 'admin/orders#index', as: 'admin_cancelled'
  get 'admin/completed', to: 'admin/orders#index', as: 'admin_completed'

  # session
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # cart
  get    'cart/new',  to: 'carts#new',   as: 'new_cart'
  get    'cart/edit', to: 'carts#edit',  as: 'edit_cart'
  get    'cart',      to: 'carts#show',  as: 'cart'
  patch  '/cart',     to: 'carts#update'
  put    '/cart',     to: 'carts#update'
  delete '/cart',     to: 'carts#destroy'
  post   '/cart',     to: 'carts#create'

  # items
  get '/items',     to: 'items#index', as: 'items'
  get '/items/:id', to: 'items#show',  as: 'item'

  # users
  get  '/users/new', to: 'users#new',    as: 'new_user'
  post '/users',     to: 'users#create', as: 'users'
  get  '/dashboard', to: 'users#show'

  # orders
  get   '/orders',     to: 'orders#index', as: 'orders'
  get   'orders/:id',  to: 'orders#show',  as: 'order'
  post  '/orders',     to: 'orders#create'
  patch '/orders/:id', to: 'orders#update'
  put   '/orders/:id', to: 'orders#update'

  # categories
  get '/categories', to: 'categories#index'
  get '/:category',  to: 'categories#show', param: :slug, as: "category"


  # RESOURCES -> previously:

  # root to:  'landing#index'

  # namespace :admin do
  #   resource  :dashboard, only: :show, controller: :dashboard
  #   resources :items,     only: :index
  #   resources :users,     only: [:show, :edit, :update]
  #   resources :items,     only: [:new, :create, :show, :edit, :update]

  #   get '/ordered',   to: 'orders#index'
  #   get '/paid',      to: 'orders#index'
  #   get '/cancelled', to: 'orders#index'
  #   get '/completed', to: 'orders#index'
  # end

  # get    '/login',     to: 'sessions#new'
  # post   '/login',     to: 'sessions#create'
  # delete '/logout',    to: 'sessions#destroy'
  # get    '/dashboard', to: 'users#show'

  # resource  :cart
  # resources :items,  only: [:index, :show]
  # resources :users,  only: [:new, :create]
  # resources :orders, only: [:index, :show, :create, :update]

  # get '/categories', to: 'categories#index'
  # get '/:category',  to: 'categories#show', param: :slug, as: "category"
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  before_action :require_admin
  helper_method :cancel?

  def show
    @orders = Order.order(:id)
  end

  def cancel?(order)
    (order.ordered? || order.paid?) && !order.cancelled?
  end
end

app/views/admin/dashboard/show.html.erb
<div class='admin-dashboard'>
  <h1><span><%= current_user.first_name %>  <%= current_user.last_name %>'s</span> Dashboard</h1>
  <%= link_to  "User Profile",     admin_user_path(current_user) %>
  <%= link_to  "View Past Orders", orders_path %>
  <%= link_to  "Edit Account",     edit_admin_user_path(current_user) %>
  <%= link_to  "Create New Item",  new_admin_item_path %>

  <table>
    <thead>
      <h1>Orders By Status</h1>
    </thead>
    <tr><%= link_to "Ordered (#{Order.total_ordered})",     admin_ordered_path(status: 0)   %></tr>
    <tr><%= link_to "Paid (#{Order.total_paid})",           admin_paid_path(status: 1)      %></tr>
    <tr><%= link_to "Cancelled (#{Order.total_cancelled})", admin_cancelled_path(status: 2) %></tr>
    <tr><%= link_to "Completed (#{Order.total_completed})", admin_completed_path(status: 3) %></tr>
  </table>

  <table>
    <thead>
      <h1>All Orders</h1>
    </thead>
    <tr>
      <th>Order ID</th>
      <th>Full Name</th>
      <th>Total Price</th>
      <th>Status</th>
      <th>Mark As</th>
      <th>Cancel Order</th>
    </tr>
    <tbody>
      <tr><% @orders.each do |order| %></tr>
      <td><%= link_to order.id, order_path(order) %></td>
      <td><%= order.user.first_name %> <%= order.user.last_name %></td>
      <td><%= number_to_currency(order.order_items.total(order)) %></td>
      <td><%= order.status %></td>
      <td>
        <% if order.ordered? %>
          <%= link_to  "paid", order_path(order, status: :paid), method: :patch, class: 'alter-status' %>
        <% elsif order.paid? %>
          <%= link_to  "completed", order_path(order, status: :completed), method: :patch, class: 'alter-status' %>
        <% end %>
      </td>
      <td>
        <% if cancel?(order) %>
          <%= link_to "cancel", order_path(order, :status => "cancelled"), method: :patch, class: 'alter-status' %>
        <% end %>
      </td>
      <% end %>
    </tbody>
  </table>

</div>