config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'landing#index', as: 'root'

  # yung namespace
  get   '/admin/dashboard',      to: 'admin/dashboard#show', as: 'admin_dashboard'

  get   '/admin/items',          to: 'admin/items#index',    as: 'admin_items'
  get   '/admin/items/new',      to: 'admin/items#new',      as: 'new_admin_item'
  get   '/admin/items/:id/edit', to: 'admin/items#edit',     as: 'edit_admin_item'
  get   '/admin/items/:id',      to: 'admin/items#show',     as: 'admin_item'
  post  '/admin/items',          to: 'admin/items#create'
  patch '/admin/items/:id',      to: 'admin/items#update'
  put   '/admin/items/:id',      to: 'admin/items#update'

  get   'admin/users/:id',      to: 'admin/users#show',  as: 'admin_user'
  get   'admin/users/:id/edit', to: 'admin/users#edit',  as: 'edit_admin_user'
  patch '/admin/users/:id',     to: 'admin/users#update'
  put   '/admin/users/:id',     to: 'admin/users#update'

  get 'admin/ordered',   to: 'admin/orders#index', as: 'admin_ordered'
  get 'admin/paid',      to: 'admin/orders#index', as: 'admin_paid'
  get 'admin/cancelled', to: 'admin/orders#index', as: 'admin_cancelled'
  get 'admin/completed', to: 'admin/orders#index', as: 'admin_completed'

  # session
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # cart
  get    'cart/new',  to: 'carts#new',   as: 'new_cart'
  get    'cart/edit', to: 'carts#edit',  as: 'edit_cart'
  get    'cart',      to: 'carts#show',  as: 'cart'
  patch  '/cart',     to: 'carts#update'
  put    '/cart',     to: 'carts#update'
  delete '/cart',     to: 'carts#destroy'
  post   '/cart',     to: 'carts#create'

  # items
  get '/items',     to: 'items#index', as: 'items'
  get '/items/:id', to: 'items#show',  as: 'item'

  # users
  get  '/users/new', to: 'users#new',    as: 'new_user'
  post '/users',     to: 'users#create', as: 'users'
  get  '/dashboard', to: 'users#show'

  # orders
  get   '/orders',     to: 'orders#index', as: 'orders'
  get   'orders/:id',  to: 'orders#show',  as: 'order'
  post  '/orders',     to: 'orders#create'
  patch '/orders/:id', to: 'orders#update'
  put   '/orders/:id', to: 'orders#update'

  # categories
  get '/categories', to: 'categories#index'
  get '/:category',  to: 'categories#show', param: :slug, as: "category"


  # RESOURCES -> previously:

  # root to:  'landing#index'

  # namespace :admin do
  #   resource  :dashboard, only: :show, controller: :dashboard
  #   resources :items,     only: :index
  #   resources :users,     only: [:show, :edit, :update]
  #   resources :items,     only: [:new, :create, :show, :edit, :update]

  #   get '/ordered',   to: 'orders#index'
  #   get '/paid',      to: 'orders#index'
  #   get '/cancelled', to: 'orders#index'
  #   get '/completed', to: 'orders#index'
  # end

  # get    '/login',     to: 'sessions#new'
  # post   '/login',     to: 'sessions#create'
  # delete '/logout',    to: 'sessions#destroy'
  # get    '/dashboard', to: 'users#show'

  # resource  :cart
  # resources :items,  only: [:index, :show]
  # resources :users,  only: [:new, :create]
  # resources :orders, only: [:index, :show, :create, :update]

  # get '/categories', to: 'categories#index'
  # get '/:category',  to: 'categories#show', param: :slug, as: "category"
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  has_many   :order_items
  has_many   :orders, through: :order_items

  validates :title,
            :description,
            :price,
            :status,
            :category_id,
            presence: true

  validates :price, numericality: { greater_than: 0 }

  validates_uniqueness_of :title

  has_attached_file :image, styles: { medium: "300x300#", thumb: "100x100#" },
  default_style: :thumb,
  default_url: ":style/defaults/default.jpg"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  enum status: [ "active", "retired" ]

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "#{@item.title} successfully created!"
      redirect_to admin_items_path
    else
      flash[:notice] = "One or more of your fields are invalid!"
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.update(params[:id], item_params)
    if item
      flash[:success] = "#{item.title} has been updated!"
      redirect_to admin_items_path
    else
      flash[:error] = "Something went wrong, please try again."
      redirect_to edit_admin_item_path
    end
  end

  private

  def item_params
    params.require(:item).permit(:title, :price, :status, :category_id, :image, :description)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/views/items/index.html.erb
<div class='items-container'>
  <% @items.each.with_index do |item, index| %>
    <div class="items items-<%= index %>">
      <h3><%= link_to  item.title, item_path(item) %></h3>
      <div class="image"><%= link_to image_tag(item.image.url(:thumb)), item_path(item) %></div>
      <p><%= item.description %></p>
      <p><%= number_to_currency(item.price) %></p>
      <%= button_to "Add to Cart", cart_path(item_id: item.id) %>
    </div>
  <% end %>
</div>

app/views/items/show.html.erb
<div class='item-show-container'>
  <div class='item-show'>
    <div class='img'>
      <%= image_tag @item.image.url(:medium), class: "image" %>
    </div>
    <div class='item-details'>
      <h1><%= @item.title %></h1>
      <h4><%= @item.category.title %></h4>
      <p>Details: <%= @item.description %></p>
      <p>Price: <%= number_to_currency(@item.price) %></p>
      <% if @item.active? %>
      <%= button_to "Add to Cart", cart_path(item_id: @item.id) %>
      <% else %>
      <%= button_to "Item Retired", cart_path(item_id: @item.id), :disabled => true %>
      <% end %>
    </div>
  </div>
  <div class='related-item-container'>
    <h3>Related Items</h3>
    <div class="related">
      <% @item.category.items.take(5).each do |item| %>
        <div class="items">
          <p><%= link_to "#{item.title}", item_path(item) %></p>
          <%= link_to image_tag(item.image.url(:thumb)), item_path(item), class: "image" %>
        </div>
      <% end %>
    </div>
  </div>
</div>